// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrIHZ2LxX0CTy8lMCQ_L6v9raEJ0ak9iU',
    appId: '1:410427123296:web:014d9fc3f258dc21384505',
    messagingSenderId: '410427123296',
    projectId: 'web-app-admin-33b9a',
    authDomain: 'web-app-admin-33b9a.firebaseapp.com',
    storageBucket: 'web-app-admin-33b9a.firebasestorage.app',
    measurementId: 'G-2H6X4WX1YE',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGGbCZD16JDGX1DQxpJ2uF8a4eWQWUE7o',
    appId: '1:410427123296:ios:1b3f1621ef06a6eb384505',
    messagingSenderId: '410427123296',
    projectId: 'web-app-admin-33b9a',
    storageBucket: 'web-app-admin-33b9a.firebasestorage.app',
    iosBundleId: 'com.example.websiteApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGGbCZD16JDGX1DQxpJ2uF8a4eWQWUE7o',
    appId: '1:410427123296:ios:1b3f1621ef06a6eb384505',
    messagingSenderId: '410427123296',
    projectId: 'web-app-admin-33b9a',
    storageBucket: 'web-app-admin-33b9a.firebasestorage.app',
    iosBundleId: 'com.example.websiteApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCrIHZ2LxX0CTy8lMCQ_L6v9raEJ0ak9iU',
    appId: '1:410427123296:web:2ffa8600a3455bb4384505',
    messagingSenderId: '410427123296',
    projectId: 'web-app-admin-33b9a',
    authDomain: 'web-app-admin-33b9a.firebaseapp.com',
    storageBucket: 'web-app-admin-33b9a.firebasestorage.app',
    measurementId: 'G-ZQ0JC32PJK',
  );

}